#Todo move to the latest graalvm, 21.3 doesnt work
FROM ghcr.io/graalvm/native-image:21.2@sha256:cdc4dd6e6dec7a4c90640233e32f86bf18b5fa50c50e0bd6aaf92a84db7a5cc2

WORKDIR /tmp/dist-arm
ADD ./output/lambda-graalvm-1.0-SNAPSHOT.jar ./app.jar
RUN $JAVA_HOME/bin/native-image -jar ./app.jar --verbose --no-fallback
RUN  microdnf install zip

ADD bootstrap bootstrap

RUN chmod +x bootstrap
#RUN chmod +x ./app

RUN zip -j function.zip bootstrap app


ENTRYPOINT ["./app"]

