version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dotnet-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wzm9l396s3ia"
s3_prefix = "dotnet-function"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = ["DotNetFunction=440457658525.dkr.ecr.us-east-2.amazonaws.com/dotnetfunction9d698c96/dotnetfunction608531e8repo"]
