POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/java/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}
###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/java-arm/book
accept: application/json
content-type: application/json

{
"name": "Sotnikov",
"author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/rust/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}
###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/rust-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/node/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/node-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/py/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/py-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/go/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}
###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/go-custom/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/go-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/dotnet/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/dotnet-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/ruby/book
accept: application/json
content-type: application/json

{
"name": "Sotnikov",
"author": "Vasil Baykoav"
}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/ruby-arm/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###

#POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/graal-arm/book
#accept: application/json
#content-type: application/json
#
#{
#"name": "Sotnikov",
#"author": "Vasil Baykoav"
#}

###
POST     https://ez5uhf2da1.execute-api.us-east-1.amazonaws.com/Prod/graal/book
accept: application/json
content-type: application/json

{
"name": "Sotnikov",
"author": "Vasil Baykoav"
}