
POST    https://{API-GATEWAY}/Prod/java/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}
###
POST    https://{API-GATEWAY}/Prod/graal/book
accept: application/json
content-type: application/json

{
"name": "Sotnikov",
"author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/rust/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/node/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/py/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/go/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/dotnet/book
accept: application/json
content-type: application/json

{
  "name": "Sotnikov",
  "author": "Vasil Baykoav"
}

###
POST    https://{API-GATEWAY}/Prod/ruby/book
accept: application/json
content-type: application/json

{
"name": "Sotnikov",
"author": "Vasil Baykoav"
}

