AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API

Resources:

  NodeJsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: node-lambda/
      Handler: lambda.create
      Runtime: nodejs14.x
      MemorySize: 256
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 10

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /node/book
            Method: post

  DotNetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dotnet-lambda/src/DotNetFunction/
      Handler: DotNetFunction::DotNetFunction.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 30

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /dotnet/book
            Method: post

  DotNetARMFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dotnet-lambda/src/DotNetFunction/
      Handler: DotNetFunction::DotNetFunction.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256
      Architectures:
        - arm64
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 30

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /dotnet/book
            Method: post

  RubyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ruby-lambda/
      Handler: app.create
      Runtime: ruby2.7
      MemorySize: 256
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Timeout: 10

      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /ruby/book
            Method: post

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: book
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/greet'
    Export:
      Name: MyServiceApiV2
